name: conqueue tests

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"
      - "**/*.html"
    branches:
      - main
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"
      - "**/*.html"
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab for debugging/testing.
  workflow_dispatch:

# Cancel in-progress actions when pushing new changes to a branch, see for more details:
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update  # ensure indexes are up-to-date
          sudo apt install ccache ninja-build

      # wget lsb-release software-properties-common gpg-agent

      #   - name: Install clang-16
      #     run: |
      #       sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" bash 16 all

      - name: Get date for ccache
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Setup ccache cache
        id: conqueue_cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-conqueue_cache-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-conqueue_cache-

      - name: Initiate ccache
        if: steps.conqueue_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.ccache
          export CCACHE_DIR=$(realpath ~/.ccache)
          ccache -sz -M 1Gi

      - name: CMake generate
        run: |
          export CCACHE_DIR=$(realpath ~/.ccache)
          ccache -s
          mkdir build
          cd build
          cmake -G Ninja .. -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: |
          cd build
          ninja -j 2
          ccache -s

      - name: Test
        run: |
          cd build
          ctest -VV --output-on-failure
